In [ ]:
import numpy as np

In [ ]:
np.asarray

In [ ]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
(a[0:2,0])

array([1, 4])

In [ ]:
a[0:2,1:3]

array([[2, 3],
       [5, 6]])

##Question 1: Given a 1D NumPy array arr_1d, extract and print the first element.
arr_1d = np.array([1, 2, 3, 4, 5])


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d[0]

1

##Question 2: Given a 1D NumPy array arr_1d, extract and print the last three elements.

arr_1d = np.array([1, 2, 3, 4, 5])


In [ ]:
arr_1d[2::]

array([3, 4, 5])

##Question 3: Given a 2D NumPy array arr_2d, extract and print the element at the second row and third column.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])



In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1,2]

6

##Question 4: Given a 2D NumPy array arr_2d, extract and print the first row.

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [ ]:
arr_2d[0]

array([1, 2, 3])

##Question 5: Given a 2D NumPy array arr_2d, extract and print the last column.


In [ ]:
arr_2d[0:3,2]

array([3, 6, 9])

##Question 6: Given a 3D NumPy array arr_3d, extract and print the element at the second matrix, third row, and third column.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
arr_3d[1,2,2]

18

##Question 7: Given a 3D NumPy array arr_3d, extract and print the first matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])


In [ ]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Question 8: Given a 3D NumPy array arr_3d, extract and print the last matrix.

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

In [ ]:
arr_3d[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])