In [3]:
import numpy as np

In [16]:
may10= np.random.randint(1,20,(8,2))

In [17]:
may11=np.transpose(may10)
print(may11)

[[17 10 16 16 14 14 10 18]
 [ 6  7 18  8 10  9 17  2]]


In [18]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [19]:
new_shape=(2,3)
b=np.reshape(a,new_shape)
print(b)

[[1 2 3]
 [4 5 6]]


In [20]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [21]:
new=(2,3,4)
b=np.resize(a,new)
print(b)

[[[1 2 3 4]
  [5 6 1 2]
  [3 4 5 6]]

 [[1 2 3 4]
  [5 6 1 2]
  [3 4 5 6]]]


In [22]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4,
       5, 6])

In [23]:
a=[1,2,3]
b=a
b[0]=10
print(a)
print(b)

[10, 2, 3]
[10, 2, 3]


In [24]:
a=[1,2,3]
b=a.copy()
b[0]=10
print(a)
print(b)

[1, 2, 3]
[10, 2, 3]


##Question 1: Transpose Array
Given a 2D NumPy array arr_2d, transpose the array and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])


In [25]:
arr_2d=np.array([[1,2,3],[4,5,6]])

In [28]:
arr2d1=np.transpose(arr_2d)
arr2d1

array([[1, 4],
       [2, 5],
       [3, 6]])

##Question 2: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 3x2 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6])



In [29]:
arr_1d = np.array([1, 2, 3, 4, 5, 6])

In [30]:
new=(3,2)
b=np.reshape(arr_1d,new)
print(b)

[[1 2]
 [3 4]
 [5 6]]


##Question 3: Resize Array
Given a 1D NumPy array arr_1d, resize it into a 3x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8]) Example Output:

Resized Array: [[1 2 3] [4 5 6] [7 8 1]]


In [4]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
new=(3,3)
c=np.resize(arr_1d,new)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

##Question 4: Flatten Array
Given a 2D NumPy array arr_2d, flatten it and print the result.

Example Input:

arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) Example Output:

Flattened Array: [1 2 3 4 5 6]


In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
arr_2d.flatten()

array([1, 2, 3, 4, 5, 6])

##Question 5: Transpose Array
Given a 3D NumPy array arr_3d, transpose the array and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

Example Output:

Transposed Array: [[[ 1 5 9] [ 2 6 10]]

[[ 3 7 11] [ 4 8 12]]]


In [10]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])

In [11]:
arr=np.transpose(arr_3d)
arr

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

##Question 6: Reshape Array
Given a 1D NumPy array arr_1d, reshape it into a 4x3 array and print the result.

Example Input:

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

Example Output:

Reshaped Array: [[ 1 2 3] [ 4 5 6] [ 7 8 9] [10 11 12]]


In [12]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [14]:
b=np.reshape(arr_1d,(4,3))
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


##Question 7: Resize Array
Given a 2D NumPy array arr_2d, resize it into a 4x4 array and print the result.

Example Input:

arr_2d = np.array([[1, 2], [3, 4]])

Example Output:

Resized Array: [[1 2 1 2] [3 4 3 4] [1 2 1 2] [3 4 3 4]]


In [15]:
arr_2d = np.array([[1, 2], [3, 4]])

In [17]:
arr=np.resize(arr_2d,(4,4))
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

##Question 8: Flatten Array
Given a 3D NumPy array arr_3d, flatten it and print the result.

Example Input:

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Example Output:

Flattened Array: [1 2 3 4 5 6 7 8]

In [18]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [19]:
arr_3d.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])